name: "Build"

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: sanitize: [On, Off]
        os: [ macos-15]
        # TODO: Enable release once we no longer have a Clang crash:
        # https://github.com/jank-lang/jank/actions/runs/12269972895/job/34234432107
        build_type: [Debug]
        include:
          - os: ubuntu-24.04
            cc: clang
            cxx: clang++
          - os: macos-13
            cc: clang
            cxx: clang++
          - os: macos-15
            cc: clang
            cxx: clang++
    runs-on: ${{ matrix.os }}
    env:
      CODECOV: ${{ matrix.codecov }}
      ANALYSIS: ${{ matrix.analysis }}
      SANITIZE: ${{ matrix.sanitize }}
      ASAN_OPTIONS: detect_leaks=0
    timeout-minutes: 240 # 4h
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and test
        uses: ./.github/actions/build
        id: build
        with:
          update_release: ${{ github.ref == 'refs/heads/main' && matrix.build_type == 'Release' }}
      - name: Update latest release
        if: success() && github.ref == 'refs/heads/main' && ${{ matrix.build_type == 'Release' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.build.outputs.release_archive }}
